---

########### Deploy AWS EC2 ##################
- name: "Deploy AWS EC2"
  hosts: localhost
  become: true
  vars:
    ansible_connection: local
  roles:
    - deploy-ec2
  tags:
    - ec2
    - deploy-ec2

############ Deploy webapp ##################
- name: "Deploy Webapp in AWS-EC2"
  hosts: "{{ host_group_name }}"
  become: true
  remote_user: ec2-user
  vars_files:
    - group_vars/all.yml
    - group_vars/secret.yml
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - deploy-webapp
  tags: 
    - webapp
    - deploy-webapp

...