---
- name: "Deploy AWS EC2"
  hosts: localhost
  become: true
  vars:
    ansible_connection: local
  roles:
    - deploy-ec2
  tags:
    - ec2
    - deploy-ec2
  
- name: "Deploy Webapp in AWS-EC2"
  hosts: "{{ host_group_name }}"
  become: true
  remote_user: centos
  vars_files:
    - group_vars/all.yml
  roles:
    - deploy-webapp
    - geerlingguy.pip
    - geerlingguy.docker
  tags: 
    - install_requirements
    - docker

  tasks:
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
      tags:
        - webapp
        - deploy-webapp

...